---
title: "Faith_Act3"
author: "Hannah Lasquite"
date: "2026-06-01"
output: html_document
---
# Set-up
getwd()
setwd("C:/Users/Acer/Desktop/LifeDat Projects")

# A.1
```{r A1, echo = TRUE, warning = TRUE}
##Read in the CSV file as a dataframe using the function “read.csv”. Make sure to clean the data prior to performing the tasks below.Do not attempt to clean the data in Excel. Perform all cleaning (e.g., NA removal) in R using the code we discussed.
rawdata<-read.csv("herpetozoa-033-095-s001.csv")

if (any(is.na(rawdata)) == T){print(sum(is.na(rawdata)))}
##To check if there is any NA values and how many

compdata <- complete.cases(rawdata)

head(rawdata[compdata, ])

herpdata <- rawdata[compdata, ]

if (any(is.na(herpdata)) == T){print(sum(is.na(herpdata)))}
##Double check if there is NA values, if nothing is printed then we good to go
```

# A.2
```{r A2, echo = TRUE, warning = TRUE}
##Show the data structure.
class(herpdata)
str(herpdata)
```

# A.3
```{r A3, echo = TRUE, warning = TRUE}
##Subset the elevation data and provide the mean, standard deviation, and range
Elev <- herpdata[,5]
mean(Elev)
sd(Elev)
range(Elev)
##Just to check if the min and max values are correct

range <- (max(Elev)-min(Elev))
range
```

# A.4
```{r A4, echo = TRUE, warning = TRUE}
##Subset the species data (columns G to AG) and count the total number of observations per species.
Obs <- herpdata[, 7:33]

##Show two methods, using a typical loop and a compact loop.
##typical ((Full credit to Jae who helped me with this part))
typObs <- 0
for(i in seq_len(ncol(Obs))) {
  typObs[i] <- (sum(Obs[i]))
}

typObstab <- matrix(typObs, nrow= 27, ncol = 1)
dimnames(typObstab) <- list(names(Obs), "Observation Sums")
typObstab
##To see the Observation Sums with the corresponding species names

##compact
compactObs <- sapply(Obs,sum)
compactObs

#Which species has the most and the fewest observations?
max(compactObs)
min(compactObs)
##shows the max and min values

which(compactObs == max(compactObs))
which(compactObs == min(compactObs))
##shows column names and column number of max and min values
```


# A.5
```{r A5, echo = TRUE, warning = TRUE}
##Combine the columns of species with the most and fewest observations with habitat types (Htypes).
herphab <- herpdata[c("Htypes","Phlo","Babu","Geat","Hety","Bosc","Drru","Apbo")]

##Determine the mean count of these species in each habitat type. 
habA <- herphab[herphab$Htypes == "ASG",-1]
habC <- herphab[herphab$Htypes == "CVT",-1]
habE <- herphab[herphab$Htypes == "ESG",-1]
habO <- herphab[herphab$Htypes == "OGF",-1]
##Subsets per habitat, removes first column indicating habitat type since it isnt needed anymore and can interfere with getting the mean observations

Amean <- sapply(habA,mean)
Cmean <- sapply(habC,mean)
Emean <- sapply(habE,mean)
Omean <- sapply(habO,mean)
##compact loop to get each mean per habitat type

habtot <- cbind(Amean, Cmean, Emean, Omean)
habtot
##To print all means in 1 matrix.OGF is the habitat with the highest mean under the Phlo species with ~15 observation average

Asum <- sapply(habA, sum)
Csum <- sapply(habC, sum)
Esum <- sapply(habE, sum)
Osum <- sapply(habO, sum)
##compact loop to get each sum per habitat type

habsum <- cbind(Asum,Csum,Esum,Osum)
habsum
##To print all sums in 1 matrix.OGF is the habitat with the highest sum under the Phlo species with 347 total observations
```

# B.1 
```{r B1, echo = TRUE, warning = TRUE}
##From the original dataframe, combine the species total count column (SPPTotal) with the elevation and habitat type columns
splotdat <- herpdata[,4:6]
splotdat

##create a scatter plot where elevation should be on the x-axis, while species total count is on the y-axis. Change the point colors based on habitat type.

splotcol <- c(ASG ="red1", CVT ="forestgreen", ESG = "navyblue", OGF="gold1")
##Choosing colors that are as different from each other as possible

plot(
  splotdat$Elev, 
  splotdat$SPPTotal, 
  col = splotcol[splotdat$Htypes], 
  pch = 10, 
  main = "Total Species Count per Elevation Level", 
  xlab = "Elevation Level", 
  ylab ="Total Species Count")

##Added a main title, x-axis title, y-axis title and changed the shape for fun also clarity

##Are there habitat types with no species observations? What are these?
##All colors are present therefore every habitat type had atleast 1 observation
```

# B.2 
```{r B2, echo = TRUE, warning = TRUE}
##From the combined data of species total counts, elevation, and habitat types, determine the total/sum number of species observed per habitat

SSPA <- sum(splotdat[splotdat$Htypes == "ASG",-(1:2)])
SSPC <- sum(splotdat[splotdat$Htypes == "CVT",-(1:2)])
SSPE <- sum(splotdat[splotdat$Htypes == "ESG",-(1:2)])
SSPO <- sum(splotdat[splotdat$Htypes == "OGF",-(1:2)])
##Subsets per habitat, removes first and second column indicating habitat type and elevation. Presence of both can interfere with the sum compact loop

bardat <- c(SSPA, SSPC, SSPE, SSPO)
##Create a bar plot (use the bar plot help) where the x-axis shows the habitat types and the y-axis shows the total species.
barplot(
  bardat, 
  names.arg = c("ASG","CVT","ESG","OGF"),
  main = "Total Species Count per Habitat", 
  xlab = "Habitat Types", 
  ylab ="Total Species Count",
  col =splotcol)
```

# B.3 
```{r B3, echo = TRUE, warning = TRUE}
##Lastly, create a histogram of total species counts using the histogram function. Make sure all axes are properly labeled.
hist(
  splotdat$SPPTotal,
  main = "Total Species Count",
  xlab = "Total Species Count",
  ylab = "Frequency",
  col ="navyblue"
)

#Added navy blue color since gray just looks sad
```

# C.1 
```{r C1, echo = TRUE, warning = TRUE}
##Based on the summary statistics and preliminary graphs you just created, how do you describe the relationship between total species observed and habitat types and elevation?

##The resulting bar graph shows that the habitats with the most species in order are ARG, OGF, ESG, and finally CVT; notably ASG has the most observations with over 50 while CVT has the least with less than 5. Based on the histogram, most sites resulted in zero observations which makes sense because of the abundance of zeros seen in the original data frame. The scatterplot reveals that there is a inverse correlation with the amount of species observed and the elevation level, the lower the elevation level the higher the species count. The elevation level also seems to determine the type of habitat present, as ASG habitats were only shown below 400 elevation, ESG only 200 and below, and OGF around 400 and above. Only two CVT sites were surveyed, the first had an elevation level below 200 and did not have any species of interest while the second had an elevation level above 600 and had 1 observation.
```
